### ISSUE TITLE
Storage System

### ISSUE THREAD

**Issue by Techtonic21** [IxGamerXL/Deltustry#14]
Infinite storage space is no more!

Add a Storage System to make players not go spam buy or smth

Ex. Containers are the lowest and Nucleus is the highest (basically, Container to Vault to Shard to Foundation then to Nucleus)

**Comment by Techtonic21** [comment]
Optional: The cores can be stackable by containers and vaults or by themselves, while containers and vaults cannot stack

**Comment by IxGamerXL** [comment]
I'm pretty sure I can add a new Equipment type that adds more inventory space. I'll just have to rig up a new type, add some failsafes so that the item cap doesn't bug out where there's more items than allowed, and I'll also add a button to set your item cap. Gold cap will also be applied to this, making the gold capacity 200. Gold cap will also be modifiable manually in the same method item cap will.

**Comment by IxGamerXL** [comment]
Finished in terms of development. It will be released soon enough.
